// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDugC8qLhKnRgYKCJ-JJvnmUCTjIGRX3uE',
    appId: '1:51318862772:web:37d6aeb7ef92ed14cdb8e1',
    messagingSenderId: '51318862772',
    projectId: 'dwelling-d96ef',
    authDomain: 'dwelling-d96ef.firebaseapp.com',
    storageBucket: 'dwelling-d96ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZ_9WAFFrgiK91WR67eBL1l8TPTTgq80',
    appId: '1:51318862772:android:d0a2eed341498ce2cdb8e1',
    messagingSenderId: '51318862772',
    projectId: 'dwelling-d96ef',
    storageBucket: 'dwelling-d96ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAmVQlOs6BTuJ8pmGbr13p6nGMGrorbM',
    appId: '1:51318862772:ios:343b9e803fab159bcdb8e1',
    messagingSenderId: '51318862772',
    projectId: 'dwelling-d96ef',
    storageBucket: 'dwelling-d96ef.appspot.com',
    iosBundleId: 'com.example.dwellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFAmVQlOs6BTuJ8pmGbr13p6nGMGrorbM',
    appId: '1:51318862772:ios:f5d26dd35c82ed3fcdb8e1',
    messagingSenderId: '51318862772',
    projectId: 'dwelling-d96ef',
    storageBucket: 'dwelling-d96ef.appspot.com',
    iosBundleId: 'com.example.dwellingApp.RunnerTests',
  );
}
